version: "3.5"
services:
  open-aps-db:
    build:
      context: ./open-aps-db
      dockerfile: Dockerfile
  open-aps-registration-site:
    build:
      context: ./registration-site
      dockerfile: Dockerfile
  open-aps-nightscout-ingester:
    build:
      context: ./nightscout-ingester
      dockerfile: Dockerfile
  open-aps-downloader:
    build:
      context: ./data-management-app
      dockerfile: Dockerfile
  metabase:
    image: metabase/metabase:latest

